# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-04 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0015_auto_20181104_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door',
            old_name='door_tree',
            new_name='door_three',
        ),
    ]
